### ISSUE TITLE
Adding support for Apple Music app

### ISSUE THREAD

**Issue by zekaizer** [xtensa/PodEmu#1]
plz support apple music
select radio and playlists

**Comment by xtensa** [comment]
I added Apple Music to the drop down list and analyzed it for use with PodEmu. Unfortunately this application behaves unlike every other music app. It does not react to button press intents and does not broadcast metadata information about currently played track. Therefore nothing could be done in PodEmu to support it, unless Apple Music developers add these 2 features.

**Comment by xtensa** [comment]
Support for Apple Music will be added through Notification Listener functionality. Stay tuned!

**Comment by xtensa** [comment]
Support for Apple Music added with version 3.0-53. It is available on Google Play.
