### ISSUE TITLE
BMW display issue. 

### ISSUE THREAD

**Issue by DeathBlade** [xtensa/PodEmu#13]
All controls seem to function but it's not displaying the data right. Not sure if this is due to my adapter or a bug itself. Car is a 2008 5 series. 

![20190416_121843](https://user-images.githubusercontent.com/1356077/56244070-de048880-6050-11e9-910f-1cf2cd1555d6.jpg)

**Comment by icstyle** [comment]
PodEmu doesn't work with the Tune2Air adapter, only custom made cable. It's all written in the manual.

**Comment by xtensa** [comment]
As icstyle wrote, PodEmu will not work with Tune2Air. Unfortunately, will not help with that.
