### ISSUE TITLE
Still Have the Dongle?

### ISSUE THREAD

**Issue by korak1111** [xtensa/PodEmu#20]
Hey sweet project! Do you still have this dongle? It is hard to source parts.  If you no longer user it we have the same car and I'd be happy to purchase it from you :)

**Comment by xtensa** [comment]
Yes, I have the dongle and yes, I am still using it and no, the parts are not difficult to find.

Please also don't use github as a forum for discussion or private requests. There is XDA  forum for this. GitHub is supposed to be used to report bugs.
