### ISSUE TITLE
Adding support for Amazon Music

### ISSUE THREAD

**Issue by redskull1986** [xtensa/PodEmu#3]
Please add support for Amazon Music/Prime Music

Thank You

**Comment by redskull1986** [comment]
Hi,

I want to ask, if you need some additional information to implement Prime Music?

**Comment by xtensa** [comment]
Support for Amazon Prime Music will be added very soon.

**Comment by xtensa** [comment]
Support for Amazon Music added with version 3.0-53. It is available on Google Play.
