### ISSUE TITLE
Feature Request: Disable (Skip) Image Download

### ISSUE THREAD

**Issue by pezcat19** [xtensa/PodEmu#5]
**Background:** The image download process is often unsuccessful on Bluetooth connections, resulting in a "lock up / frozen" state. When the image does successfully download, the PodEmu features and playback work correctly.

**Request:** Can you please add a "Disable Image Download" option to bypass this step, and increase the chances of successful connections via Bluetooth. 

Thanks in advance! :)

**Comment by pezcat19** [comment]
**Additional Feature suggestion:** 

With the logo download set to "disabled", the connection between the Android device and the iPod car dock starts automatically VERY quickly after initial power-up (this is a good thing). Sometimes, this is too quick for the Bluetooth audio modules to connect, which can in-turn confuse the music player app (Google Play Music in this case.) 

The symptom is that the iPod connection is connects and works properly, but the music audio is playing directly from the Android phone speakers, because the BT Audio Module has not had enough time to connect to the android phone yet. When it does connect (after some 10-30 seconds usually), Google Play Music will re-start the current playing track from the beginning, or jump a track forward or backwards whenever the BT Audio Module is connected. 

In my case, this makes the initial connection is a bit erratic, as the track jumps forward and back, pauses, etc, for 10-20 seconds until everything settles down. Then it works correctly. 

**Suggestion** : can you add a user configurable delay in the app to "_Auto switch to controlled app after N seconds delay_" option? This would allow the iPod interface to stabilize and connect to the BT Audio Module before the music playback begins. 

**OR**, would an option for "_Delay all music playback until BT Audio Module is connected_" option achieve the same result more easily?

Thanks again

**Comment by xtensa** [comment]
Option to disable image download added to "production".

As for your second issue, it is very specific to car/music app/android version. So adding a delay might not be the best solution here. It will probably cause communication errors with the car. I tested it on my phone and connecting BT audio device with delay does not affect playback status (the track is not paused or rewinded).
